spring:
  application:
    name: scd-foo-service

server:
  port: 6101

eureka:
  client:
    service-url:
      'defaultZone': http://scd-eureka:6001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: scd-foo-service-6101

feign:
  client:
    config:
      default:
        loggerLevel: basic
      scd-bar-service:
        loggerLevel: full
