version: '2.2'

services:
  scd-eureka:
    image: scd-eureka
    ports:
      - "6001:6001"
  scd-zuul:
    image: scd-zuul
    links:
      - scd-eureka
    ports:
      - "6002:6002"
  scd-foo-service:
    image: scd-foo-service
    links:
      - scd-eureka
  scd-bar-service:
    image: scd-bar-service
    scale: 2
    links:
      - scd-eureka
